# Generated by Django 5.2 on 2025-04-16 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_name_project_title_project_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="core.customer",
            ),
        ),
    ]
