# Generated by Django 5.2 on 2025-04-17 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_project_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectfile",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="core.project",
            ),
        ),
    ]
